apiVersion: v1
kind: Secret
metadata:
  name: payments-secrets
  namespace: fcg
type: Opaque
stringData:
  # Database Connection String
  ConnectionStrings__DefaultConnection: "Host=34.39.196.255;Port=5432;Database=fcg_payments;Username=postgres;Password=081160Ec!;Timeout=30;SSL Mode=Disable"
  
  # JWT Key
  Jwt__Key: "LHQ2+uXWaOMKwI+4h6gI9Zx7tkdUONRMkWa3eAKQxkv0CQLtaUOwZzPqcJ27jsgV"
  
  # RabbitMQ Credentials
  Messaging__Username: "fcg"
  Messaging__Password: "081160Ec!"
  RabbitMqConnection: "amqp://fcg:081160Ec!@rabbitmq.fcg.svc.cluster.local:5672"
  
  # Application Insights Connection String
  ApplicationInsights__ConnectionString: "InstrumentationKey=f0c4439c-e3bb-4971-b133-46ee4e657f04;IngestionEndpoint=https://brazilsouth-1.in.applicationinsights.azure.com/;LiveEndpoint=https://brazilsouth.livediagnostics.monitor.azure.com/;ApplicationId=79c04893-3742-4314-9dcf-887da8509f65"
